import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Spaghetti",
    category: "african",
    price: 180,
    image: "/spaghetti-chicken.jpg",
    description: "Delicious spaghetti with rich tomato sauce and herbs",
    longDescription:
      "Our signature spaghetti is cooked to perfection with a rich tomato sauce, fresh herbs, and your choice of protein. A classic favorite that never disappoints.",
    addOns: [
      { id: 1, name: "Extra Meat", price: 30 },
      { id: 2, name: "Extra Cheese", price: 15 },
      { id: 3, name: "Garlic Bread", price: 20 },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 2,
    name: "Whole Chicken",
    category: "african",
    price: 250,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Crispy%20chicken-BFtcL5JRoOIwyW3VS0KskBDzF7haUY.jpg",
    description: "Perfectly roasted whole chicken with seasoning",
    longDescription:
      "A full roasted chicken seasoned with our special blend of spices. Served with crispy fries. Perfect for sharing with family and friends.",
    addOns: [
      { id: 4, name: "Extra Sauce", price: 10 },
      { id: 5, name: "Fried Plantain", price: 15 },
      { id: 6, name: "Coleslaw", price: 10 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 198,
  },
  {
    id: 3,
    name: "Half Chicken",
    category: "african",
    price: 150,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Half%20chinken-5w6YI99FHKXkt6lwvEzNavI8hmwszB.jpg",
    description: "Half roasted chicken with special seasoning",
    longDescription:
      "Half of our perfectly roasted chicken, ideal for a single serving or smaller appetite. Seasoned to perfection.",
    addOns: [
      { id: 7, name: "Extra Sauce", price: 10 },
      { id: 8, name: "Fried Plantain", price: 15 },
      { id: 9, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: 4,
    name: "Bulgur with Fish",
    category: "african",
    price: 250,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bulgur-51MinKIMuIfRwxBQGL3GKgxQyl9lm5.jpg",
    description: "Nutritious bulgur wheat served with fresh fish",
    longDescription:
      "Healthy bulgur wheat cooked with vegetables and served with perfectly seasoned fish. A nutritious and delicious meal.",
    addOns: [
      { id: 10, name: "Extra Fish", price: 40 },
      { id: 11, name: "Extra Vegetables", price: 15 },
    ],
    featured: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 5,
    name: "Fried Rice and Fish",
    category: "african",
    price: 250,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fried%20rice%20and%20grilled%C2%A0fish-zVGHhUODDMEYCSfeMWa5d70h6WrkXE.jpg",
    description: "Flavorful fried rice with seasoned grilled fish",
    longDescription:
      "Our special fried rice loaded with vegetables and served with perfectly grilled fish, fresh coleslaw, and fried plantains. A complete and satisfying meal.",
    addOns: [
      { id: 12, name: "Extra Fish", price: 40 },
      { id: 13, name: "Plantain", price: 15 },
    ],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 6,
    name: "Fried Rice and Chicken",
    category: "african",
    price: 180,
    image: "/fried-rice-chicken.jpg",
    description: "Tasty fried rice with tender chicken",
    longDescription:
      "Delicious fried rice with mixed vegetables and tender chicken pieces. A popular choice for lunch or dinner.",
    addOns: [
      { id: 14, name: "Extra Chicken", price: 30 },
      { id: 15, name: "Coleslaw", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 212,
  },
  {
    id: 7,
    name: "Shawarma Meat",
    category: "fast-food",
    price: 120,
    image: "/roast-meat-skewers.jpg",
    description: "Delicious meat shawarma wrap with fresh vegetables",
    longDescription:
      "Tender marinated meat wrapped in fresh pita bread with lettuce, tomatoes, onions, and our special sauce.",
    addOns: [
      { id: 16, name: "Extra Meat", price: 30 },
      { id: 17, name: "Extra Sauce", price: 5 },
      { id: 18, name: "Fries", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 245,
  },
  {
    id: 8,
    name: "Shawarma Chicken",
    category: "fast-food",
    price: 100,
    image: "/chicken-shawarma-wrap-garlic-sauce.jpg",
    description: "Tasty chicken shawarma with fresh toppings",
    longDescription:
      "Grilled chicken wrapped in soft pita with crisp vegetables and our signature garlic sauce. A customer favorite!",
    addOns: [
      { id: 19, name: "Extra Chicken", price: 25 },
      { id: 20, name: "Extra Sauce", price: 5 },
      { id: 21, name: "Fries", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 278,
  },
  {
    id: 9,
    name: "Burger",
    category: "fast-food",
    price: 100,
    image: "/classic-beef-burger-lettuce-tomato.jpg",
    description: "Classic beef burger with fresh toppings",
    longDescription:
      "Juicy beef patty with lettuce, tomato, onions, pickles, and our special burger sauce on a toasted bun.",
    addOns: [
      { id: 22, name: "Extra Patty", price: 30 },
      { id: 23, name: "Cheese", price: 10 },
      { id: 24, name: "Bacon", price: 15 },
    ],
    rating: 4.6,
    reviewCount: 201,
  },
  {
    id: 10,
    name: "Egg Burger",
    category: "fast-food",
    price: 120,
    image: "/burger-with-fried-egg-beef-patty.jpg",
    description: "Burger with fried egg and beef patty",
    longDescription:
      "Our classic burger topped with a perfectly fried egg. The combination of runny yolk and juicy beef is irresistible!",
    addOns: [
      { id: 25, name: "Extra Egg", price: 15 },
      { id: 26, name: "Cheese", price: 10 },
      { id: 27, name: "Fries", price: 20 },
    ],
    rating: 4.7,
    reviewCount: 192,
  },
  {
    id: 11,
    name: "Double Burger",
    category: "fast-food",
    price: 170,
    image: "/double-beef-burger-cheese-stacked.jpg",
    description: "Double beef patty burger for big appetites",
    longDescription:
      "Two juicy beef patties stacked high with cheese, lettuce, tomato, and our special sauce. For those with a hearty appetite!",
    addOns: [
      { id: 28, name: "Extra Patty", price: 40 },
      { id: 29, name: "Bacon", price: 15 },
      { id: 30, name: "Fries", price: 20 },
    ],
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 12,
    name: "Ice Cream Small",
    category: "drinks",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cream-LLQ3LSvijGkqTbPBJicnaMTQOfwUgs.jpg",
    description: "Small serving of creamy ice cream",
    longDescription: "Cool and creamy ice cream in various flavors. Perfect for a sweet treat!",
    addOns: [
      { id: 31, name: "Extra Scoop", price: 10 },
      { id: 32, name: "Toppings", price: 5 },
    ],
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: 13,
    name: "Ice Cream Large",
    category: "drinks",
    price: 50,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cream%201-KUmozZfzOikgIjvuN7kYWfQnJAwe2X.jpg",
    description: "Large serving of delicious ice cream",
    longDescription:
      "Generous portion of our creamy ice cream. Available in multiple flavors to satisfy your sweet tooth.",
    addOns: [
      { id: 33, name: "Extra Scoop", price: 15 },
      { id: 34, name: "Toppings", price: 8 },
    ],
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: 14,
    name: "Foofoo with Okra Soup",
    category: "african",
    price: 120,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Foofoo%20okara%20suap-UMxkpqwGcyF8Q9iT8MnWbotSFxipD6.jpg",
    description: "Traditional African foofoo with okra soup",
    longDescription:
      "Smooth and stretchy foofoo served with rich okra soup and tender meat. A traditional African staple that's both filling and delicious.",
    addOns: [
      { id: 35, name: "Extra Foofoo", price: 30 },
      { id: 36, name: "Extra Soup", price: 25 },
      { id: 37, name: "Fish", price: 30 },
    ],
    rating: 4.7,
    reviewCount: 145,
  },
  {
    id: 15,
    name: "Birthday Cake Small",
    category: "bakery",
    price: 350,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20cake%20350-M9U0vI1CYXs9XJxgZXxB7qCn89LYIl.jpg",
    description: "Small birthday cake for intimate celebrations",
    longDescription:
      "Beautiful birthday cake perfect for small gatherings. Available in various flavors and can be customized with a message.",
    addOns: [
      { id: 38, name: "Custom Message", price: 10 },
      { id: 39, name: "Candles", price: 5 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: 16,
    name: "Birthday Cake Medium",
    category: "bakery",
    price: 550,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20Cake%20550-aDjYxWfat7XZ0J5d4puKB8EI4ydk1Y.jpg",
    description: "Medium birthday cake for family celebrations",
    longDescription:
      "Perfect sized cake for family birthday celebrations. Choose from chocolate, vanilla, or red velvet flavors. Can be customized with your child's favorite themes!",
    addOns: [
      { id: 40, name: "Custom Message", price: 10 },
      { id: 41, name: "Candles", price: 5 },
    ],
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: 17,
    name: "Birthday Cake Large",
    category: "bakery",
    price: 750,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20cake%202500-scV0HFXBrDDXf02a6v4vFb4SuVHEpM.jpg",
    description: "Large birthday cake for big celebrations",
    longDescription:
      "Large celebration cake perfect for parties. Beautifully decorated with intricate designs. Multiple flavor options available.",
    addOns: [
      { id: 42, name: "Custom Message", price: 15 },
      { id: 43, name: "Candles", price: 8 },
    ],
    rating: 5.0,
    reviewCount: 87,
  },
  {
    id: 18,
    name: "Birthday Cake Extra Large",
    category: "bakery",
    price: 1000,
    image: "/placeholder.svg?height=400&width=400",
    description: "Extra large cake for grand celebrations",
    longDescription:
      "Our grandest birthday cake for large celebrations. Stunning design and exceptional taste. Perfect for milestone birthdays!",
    addOns: [
      { id: 44, name: "Custom Message", price: 20 },
      { id: 45, name: "Candles", price: 10 },
    ],
    rating: 5.0,
    reviewCount: 65,
  },
  {
    id: 19,
    name: "Rich Cake",
    category: "bakery",
    price: 50,
    image: "/rich-cake-trays.jpg",
    description: "Moist and rich cake slice",
    longDescription:
      "Dense, moist, and incredibly rich cake. Perfect with a cup of tea or coffee. A decadent treat for any time of day.",
    addOns: [
      { id: 46, name: "Extra Slice", price: 50 },
      { id: 47, name: "Ice Cream", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 20,
    name: "Banana Bread Small",
    category: "bakery",
    price: 65,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Banana%20bread-GQZfy18LuYq3tX05fv2wxGMBeIFoNZ.jpg",
    description: "Small loaf of homemade banana bread",
    longDescription:
      "Moist and flavorful banana bread made with ripe bananas. Perfect for breakfast or as a snack with tea.",
    addOns: [
      { id: 48, name: "Butter", price: 5 },
      { id: 49, name: "Extra Slice", price: 15 },
    ],
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 21,
    name: "Banana Bread Large",
    category: "bakery",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bread-UUbU7HgbudqXE1hzdVfaLMN74DHaGO.jpg",
    description: "Large loaf of homemade banana bread",
    longDescription:
      "Full-sized loaf of our delicious banana bread. Great for sharing or enjoying throughout the week.",
    addOns: [
      { id: 50, name: "Butter", price: 8 },
      { id: 51, name: "Jam", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 145,
  },
  {
    id: 22,
    name: "Pizza",
    category: "fast-food",
    price: 120,
    image: "/pizza.jpg",
    description: "Delicious pepperoni pizza with melted cheese",
    longDescription:
      "Hot and fresh pizza loaded with pepperoni, mozzarella cheese, and our signature tomato sauce. Perfectly baked with a crispy crust.",
    addOns: [
      { id: 52, name: "Extra Cheese", price: 20 },
      { id: 53, name: "Extra Pepperoni", price: 25 },
      { id: 54, name: "Mushrooms", price: 15 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 23,
    name: "Sausage Roll",
    category: "bakery",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chin%20chin-rKdwF22BAMnuJCF9I9uLYv5dT6btdf.jpg",
    description: "Freshly baked sausage rolls",
    longDescription:
      "Golden brown sausage rolls made fresh daily. Flaky pastry wrapped around seasoned sausage meat. Perfect for a quick snack!",
    addOns: [
      { id: 55, name: "Extra Roll", price: 20 },
      { id: 56, name: "Ketchup", price: 5 },
    ],
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: 24,
    name: "Red Bull",
    category: "drinks",
    price: 60,
    image: "/redbull.jpeg",
    description: "Red Bull Energy Drink",
    longDescription: "Ice cold Red Bull energy drink to keep you energized throughout the day.",
    addOns: [],
    rating: 4.6,
    reviewCount: 78,
  },
  {
    id: 25,
    name: "Vimto",
    category: "drinks",
    price: 35,
    image: "/vimto-drink.jpg",
    description: "Vimto Sparkling Drink",
    longDescription: "Refreshing Vimto sparkling drink with mixed fruit flavors. A delicious and fizzy treat!",
    addOns: [],
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: 26,
    name: "Soft Drinks",
    category: "drinks",
    price: 35,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cock-OKpuLbq3Smq9JWt4x6RgSVjxpF7N2A.jpeg",
    description: "Coca-Cola, Sprite, or Fanta",
    longDescription: "Choose from Coca-Cola, Sprite, or Fanta Orange. Ice cold and refreshing!",
    addOns: [],
    rating: 4.7,
    reviewCount: 234,
  },
  {
    id: 27,
    name: "Super Malt",
    category: "drinks",
    price: 65,
    image: "/super-malt.jpg",
    description: "Super Malt Original",
    longDescription:
      "Non-alcoholic malt beverage with B vitamins. Rich, smooth taste that's both nutritious and delicious.",
    addOns: [],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 28,
    name: "Fanta",
    category: "drinks",
    price: 35,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cold%20fanta-qQNGGuht2bRfqVLzznJhdI4U1UuyqA.jpeg",
    description: "Ice Cold Fanta Orange",
    longDescription: "Refreshing ice-cold Fanta Orange soda. Perfect for quenching your thirst on a hot day!",
    addOns: [],
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 29,
    name: "Kebba",
    category: "african",
    price: 25,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kebba-wTBvhmk8yXmeOjmIfqX8qW9QHd2hTA.jpg",
    description: "Traditional African Kebba",
    longDescription:
      "Delicious traditional African kebba, crispy on the outside and flavorful on the inside. A beloved street food delicacy!",
    addOns: [
      { id: 57, name: "Extra Sauce", price: 5 },
      { id: 58, name: "Extra Pieces", price: 30 },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: 30,
    name: "Laffadie Special",
    category: "african",
    price: 150,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Laffadie%20150-g20b02jrCgZ6rwZHy1YCStGigAa16y.jpg",
    description: "Laffadie rice with sausages and fried items",
    longDescription:
      "A complete Laffadie meal featuring white rice, sausages, crispy fried items, and special spices. A hearty traditional favorite!",
    addOns: [
      { id: 59, name: "Extra Sausage", price: 20 },
      { id: 60, name: "Extra Rice", price: 15 },
    ],
    rating: 4.9,
    reviewCount: 187,
  },
  {
    id: 31,
    name: "Maltina",
    category: "drinks",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Maltina-w1L5rUpnTXcQXagYGs4YutmG3FQMgp.jpeg",
    description: "Maltina Classic Malt Drink",
    longDescription: "Enriched non-alcoholic malt beverage with B vitamins. Smooth, refreshing, and nutritious!",
    addOns: [],
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: 32,
    name: "Lucozade Energy",
    category: "drinks",
    price: 35,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lucozade%20Drink-FMcU3DK8mTtSzZPDnQa37vEbURrpsD.jpg",
    description: "Lucozade Energy Orange",
    longDescription:
      "Ice-cold Lucozade Energy drink with glucose to keep you powered throughout the day. Refreshing orange flavor!",
    addOns: [],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 33,
    name: "Krain Krain",
    category: "african",
    price: 200,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/krain%20krain-6wBSS2WtipNx50vqemm8Zi3hrhP0JZ.jpg",
    description: "Traditional Krain Krain stew with meat",
    longDescription:
      "Rich, traditional Krain Krain stew cooked with tender meat, seafood, and special spices. A West African delicacy from Pee's Bakery!",
    addOns: [
      { id: 61, name: "Extra Meat", price: 40 },
      { id: 62, name: "Extra Seafood", price: 50 },
      { id: 63, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 143,
  },
  {
    id: 34,
    name: "Grilled Catfish with Fried Rice",
    category: "african",
    price: 400,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Grilled%20catfish%20with%20fried%20rice%20and%20plaintain%20and%C2%A0coslaw-6H4vAZg1XfIGxCydDCkLe20o2m4jpp.jpg",
    description: "Whole grilled catfish with fried rice, plantain and coleslaw",
    longDescription:
      "A complete seafood feast featuring a whole grilled catfish, flavorful fried rice, sweet fried plantains, and fresh coleslaw. Served with special sauces!",
    addOns: [
      { id: 64, name: "Extra Fish", price: 100 },
      { id: 65, name: "Extra Plantain", price: 20 },
      { id: 66, name: "Extra Rice", price: 30 },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 289,
  },
  {
    id: 35,
    name: "Fish in Batter",
    category: "african",
    price: 25,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fishing%20Batter%20Small%20Size%2025%20big%20size%C2%A035-Z6IS39YBpuHTxJAmZTVDq90WQHYIS8.jpg",
    description: "Crispy fried fish with golden batter",
    longDescription:
      "Perfectly fried fish with a crispy golden batter. Small size 25 GMD, big size 35 GMD. A delicious and satisfying meal!",
    addOns: [
      { id: 67, name: "Extra Sauce", price: 10 },
      { id: 68, name: "Fries", price: 20 },
      { id: 69, name: "Coleslaw", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 145,
  },
  {
    id: 36,
    name: "Don Simon Juice",
    category: "drinks",
    price: 85,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Don%20Simon%20Juice-88SdYDRmIs8GYpBEz7KZtdMd9uaZcI.jpg",
    description: "Don Simon Multifrutas Juice 1L",
    longDescription:
      "Refreshing multi-fruit juice from Don Simon. Made with a blend of delicious fruits. Perfect for any meal!",
    addOns: [],
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: 37,
    name: "Fish Balls",
    category: "african",
    price: 10,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chinken%20ball-N3e39zDXyjn2ea2B27wlFUEaHqGP8n.jpg",
    description: "Crispy fried fish balls - 10 GMD for 1pc, 100 GMD for 12pcs with veg",
    longDescription:
      "Golden fried fish balls made with fresh fish and special seasonings. Crispy on the outside, tender on the inside. A popular snack! 10 GMD for 1 piece or 100 GMD for 12 pieces with vegetables.",
    addOns: [
      { id: 70, name: "Extra Sauce", price: 5 },
      { id: 71, name: "12 Pieces with Veg", price: 90 },
    ],
    rating: 4.6,
    reviewCount: 134,
  },
  {
    id: 38,
    name: "Grilled Gizzards",
    category: "african",
    price: 20,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gizzard%20on%20stick%202-CpR92jBXH9n5YvcFIM5phYsAHBK8Ff.jpg",
    description: "Spicy grilled gizzards",
    longDescription:
      "Tender chicken gizzards marinated in spices and grilled to perfection. A flavorful street food favorite!",
    addOns: [
      { id: 72, name: "Extra Stick", price: 20 },
      { id: 73, name: "Extra Sauce", price: 10 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 187,
  },
  {
    id: 39,
    name: "Ceres Mango Juice",
    category: "drinks",
    price: 100,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ceres%20Mango%20Juice%20-JGq6n8HpqV7dzyop1xwElwLYRXLioz.jpg",
    description: "100% Juice blend - Mango flavor 1L",
    longDescription:
      "Refreshing 100% pear juice from concentrate and mango puree. Natural and delicious tropical flavor in a 1L carton.",
    addOns: [],
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 40,
    name: "Archeka with Grilled Fish",
    category: "african",
    price: 350,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Archeka%20with%20fish-lHyZlsK3FM4hJE73dgDzLfyzxUpFS2.jpg",
    description: "Couscous-style archeka with whole grilled fish",
    longDescription:
      "Traditional archeka (couscous) served with perfectly grilled fish, golden fried plantains, fresh garden salad, and special sauces. A complete and nutritious meal!",
    addOns: [
      { id: 74, name: "Extra Fish", price: 80 },
      { id: 75, name: "Extra Plantain", price: 20 },
      { id: 76, name: "Extra Archeka", price: 25 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: 41,
    name: "Archeka with Grilled Chicken",
    category: "african",
    price: 250,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Archeka%20and%20chicken%C2%A0-hm1HnDJoEzP2Qan9GmIMB2gL8cvA4K.jpg",
    description: "Couscous-style archeka with grilled chicken",
    longDescription:
      "Fluffy archeka (couscous) served with tender grilled chicken, boiled eggs, sliced meats, fresh vegetables, and homemade sauces. A hearty and satisfying platter!",
    addOns: [
      { id: 77, name: "Extra Chicken", price: 60 },
      { id: 78, name: "Extra Eggs", price: 15 },
      { id: 79, name: "Extra Archeka", price: 25 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 189,
  },
  {
    id: 42,
    name: "Cassava Leaf Stew",
    category: "african",
    price: 180,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/African%20dish%20Cassava%20Leafe-Jj1jMyPWwCCeN6LUZlPKXufg46kTos.jpg",
    description: "Traditional West African cassava leaf stew",
    longDescription:
      "Rich and flavorful cassava leaf stew cooked with tender meat, fish, and authentic West African spices. Served in convenient containers. A traditional delicacy from Pee's Bakery!",
    addOns: [
      { id: 80, name: "Extra Meat", price: 40 },
      { id: 81, name: "Rice", price: 20 },
      { id: 82, name: "Foofoo", price: 30 },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 167,
  },
  {
    id: 43,
    name: "Archeka with Goat",
    category: "african",
    price: 450,
    image: "/archeka-with-grilled-goat-meat.jpg",
    description: "Couscous-style archeka with grilled goat meat",
    longDescription:
      "Traditional archeka (couscous) served with tender grilled goat meat, plantains, vegetables, and special sauces. A premium and flavorful meal!",
    addOns: [
      { id: 83, name: "Extra Goat", price: 100 },
      { id: 84, name: "Extra Plantain", price: 20 },
      { id: 85, name: "Extra Archeka", price: 25 },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 45,
  },
  {
    id: 44,
    name: "Chicken Balls",
    category: "fast-food",
    price: 80,
    image: "/crispy-chicken-balls.jpg",
    description: "Pack of 12 crispy chicken balls with vegetables",
    longDescription:
      "Golden fried chicken balls made with tender chicken and special seasonings. Pack of 12 pieces served with fresh vegetables. Perfect for sharing!",
    addOns: [
      { id: 86, name: "Extra Sauce", price: 5 },
      { id: 87, name: "Extra Vegetables", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: 45,
    name: "Meat Pie",
    category: "bakery",
    price: 20,
    image: "/meat-pie.jpg",
    description: "Freshly baked meat pie",
    longDescription:
      "Flaky pastry filled with seasoned ground beef and vegetables. Baked fresh daily. Perfect for a quick snack or light meal!",
    addOns: [
      { id: 88, name: "Extra Pie", price: 20 },
      { id: 89, name: "Ketchup", price: 5 },
    ],
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 46,
    name: "Roast Meat",
    category: "african",
    price: 35,
    image: "/roasted-meat-on-skewer.jpg",
    description: "Tender roasted meat on skewer",
    longDescription:
      "Succulent pieces of roasted meat seasoned with African spices and grilled to perfection. A delicious street food favorite!",
    addOns: [
      { id: 90, name: "Extra Skewer", price: 35 },
      { id: 91, name: "Extra Sauce", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 178,
  },
  {
    id: 47,
    name: "Pork Stick",
    category: "african",
    price: 35,
    image: "/grilled-pork-on-stick.jpg",
    description: "Grilled pork on stick",
    longDescription:
      "Tender pork pieces marinated and grilled on skewers. Juicy, flavorful, and perfectly seasoned. A popular street food choice!",
    addOns: [
      { id: 92, name: "Extra Stick", price: 35 },
      { id: 93, name: "Extra Sauce", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 48,
    name: "Spring Roll",
    category: "fast-food",
    price: 10,
    image: "/crispy-spring-roll.jpg",
    description: "Crispy vegetable spring roll",
    longDescription:
      "Crispy fried spring rolls filled with mixed vegetables and special seasonings. Perfect as a snack or appetizer!",
    addOns: [
      { id: 94, name: "Extra Roll", price: 10 },
      { id: 95, name: "Sweet Chili Sauce", price: 5 },
    ],
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: 49,
    name: "Crispy Chicken",
    category: "african",
    price: 35,
    image: "/crispy-fried-chicken.png",
    description: "Crispy fried chicken pieces",
    longDescription:
      "Golden fried chicken with a crispy coating. Seasoned to perfection with our special blend of spices. Juicy and flavorful!",
    addOns: [
      { id: 96, name: "Extra Piece", price: 35 },
      { id: 97, name: "Fries", price: 20 },
      { id: 98, name: "Coleslaw", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 201,
  },
  {
    id: 50,
    name: "Bread",
    category: "bakery",
    price: 25,
    image: "/fresh-baked-bread-loaf.jpg",
    description: "Fresh baked bread loaf",
    longDescription:
      "Soft and fresh white bread loaf baked daily. Perfect for sandwiches or toast. Made with quality ingredients!",
    addOns: [
      { id: 99, name: "Butter", price: 5 },
      { id: 100, name: "Jam", price: 8 },
    ],
    rating: 4.5,
    reviewCount: 123,
  },
  {
    id: 51,
    name: "Brown Bread",
    category: "bakery",
    price: 35,
    image: "/whole-wheat-brown-bread.jpg",
    description: "Healthy whole wheat brown bread",
    longDescription:
      "Nutritious brown bread made with whole wheat flour. Higher in fiber and perfect for a healthy diet. Freshly baked!",
    addOns: [
      { id: 101, name: "Butter", price: 5 },
      { id: 102, name: "Honey", price: 10 },
    ],
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 52,
    name: "Grilled Catfish with Fries",
    category: "african",
    price: 350,
    image: "/grilled-catfish-with-fries-plantain-coleslaw.jpg",
    description: "Whole grilled catfish with fries, plantain and coleslaw",
    longDescription:
      "Perfectly grilled whole catfish served with crispy fries, sweet fried plantains, and fresh coleslaw. A delicious seafood platter!",
    addOns: [
      { id: 103, name: "Extra Fish", price: 100 },
      { id: 104, name: "Extra Plantain", price: 20 },
      { id: 105, name: "Extra Fries", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 167,
  },
  {
    id: 53,
    name: "Grilled Fish",
    category: "african",
    price: 350,
    image: "/grilled-whole-fish.jpg",
    description: "Whole grilled fish - 350 GMD or 550 GMD depending on size",
    longDescription:
      "Fresh whole fish grilled to perfection with our special blend of spices. Available in regular (350 GMD) or large (550 GMD) sizes. Served with sides!",
    addOns: [
      { id: 106, name: "Large Size", price: 200 },
      { id: 107, name: "Extra Sauce", price: 10 },
      { id: 108, name: "Plantain", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 54,
    name: "Chin Chin",
    category: "bakery",
    price: 20,
    image: "/chin-chin-west-african-snack.jpg",
    description: "Crunchy West African chin chin",
    longDescription:
      "Traditional West African crunchy snack made with flour, sugar, and spices. Sweet, crispy, and perfect for munching anytime!",
    addOns: [{ id: 109, name: "Extra Portion", price: 20 }],
    rating: 4.7,
    reviewCount: 145,
  },
]

export const categories = [
  { id: "all", name: "All Items" },
  { id: "african", name: "African Dishes" },
  { id: "bakery", name: "Bakery & Cakes" },
  { id: "fast-food", name: "Burgers & Shawarma" },
  { id: "drinks", name: "Drinks & Desserts" },
]
