import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Spaghetti",
    category: "african",
    price: 180,
    image: "/spaghetti-chicken.jpg",
    description: "Delicious spaghetti with rich tomato sauce and herbs",
    longDescription:
      "Our signature spaghetti is cooked to perfection with a rich tomato sauce, fresh herbs, and your choice of protein. A classic favorite that never disappoints.",
    addOns: [
      { id: 1, name: "Extra Meat", price: 30 },
      { id: 2, name: "Extra Cheese", price: 15 },
      { id: 3, name: "Garlic Bread", price: 20 },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 2,
    name: "Whole Chicken",
    category: "african",
    price: 250,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202025-11-06%20at%2019.18.26_707a395d-9EYS1emRSX3gUjhli9aYKrldsybBp4.jpg",
    description: "Perfectly roasted whole chicken with seasoning",
    longDescription:
      "A full roasted chicken seasoned with our special blend of spices. Served with crispy fries. Perfect for sharing with family and friends.",
    addOns: [
      { id: 4, name: "Extra Sauce", price: 10 },
      { id: 5, name: "Fried Plantain", price: 15 },
      { id: 6, name: "Coleslaw", price: 10 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 198,
  },
  {
    id: 3,
    name: "Half Chicken",
    category: "african",
    price: 150,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Half%20chinken-5w6YI99FHKXkt6lwvEzNavI8hmwszB.jpg",
    description: "Half roasted chicken with special seasoning",
    longDescription:
      "Half of our perfectly roasted chicken, ideal for a single serving or smaller appetite. Seasoned to perfection.",
    addOns: [
      { id: 7, name: "Extra Sauce", price: 10 },
      { id: 8, name: "Fried Plantain", price: 15 },
      { id: 9, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: 4,
    name: "Bulgur with Fish",
    category: "african",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bulgur-51MinKIMuIfRwxBQGL3GKgxQyl9lm5.jpg",
    description: "Nutritious bulgur wheat served with fresh fish",
    longDescription:
      "Healthy bulgur wheat cooked with vegetables and served with perfectly seasoned fish. A nutritious and delicious meal.",
    addOns: [
      { id: 10, name: "Extra Fish", price: 40 },
      { id: 11, name: "Extra Vegetables", price: 15 },
    ],
    featured: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 5,
    name: "Fried Rice and Fish",
    category: "african",
    price: 100,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fried%20rice%20and%20grilled%C2%A0fish-zVGHhUODDMEYCSfeMWa5d70h6WrkXE.jpg",
    description: "Flavorful fried rice with seasoned grilled fish",
    longDescription:
      "Our special fried rice loaded with vegetables and served with perfectly grilled fish, fresh coleslaw, and fried plantains. A complete and satisfying meal.",
    addOns: [
      { id: 12, name: "Extra Fish", price: 40 },
      { id: 13, name: "Plantain", price: 15 },
    ],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 6,
    name: "Fried Rice and Chicken",
    category: "african",
    price: 180,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fride%20Rice%20and%20chicken-TfVnP2SbQUXowmurXJXkzo1DxPxtJM.jpg",
    description: "Tasty fried rice with tender chicken",
    longDescription:
      "Delicious fried rice with mixed vegetables and tender chicken pieces. A popular choice for lunch or dinner.",
    addOns: [
      { id: 14, name: "Extra Chicken", price: 30 },
      { id: 15, name: "Coleslaw", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 212,
  },
  {
    id: 7,
    name: "Shawarma Meat",
    category: "fast-food",
    price: 120,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-81A5dnbk4YmP5xpjCKx1RaTXxhXLTi.png",
    description: "Delicious meat shawarma wrap with fresh vegetables",
    longDescription:
      "Tender marinated meat wrapped in fresh pita bread with lettuce, tomatoes, onions, and our special sauce.",
    addOns: [
      { id: 16, name: "Extra Meat", price: 30 },
      { id: 17, name: "Extra Sauce", price: 5 },
      { id: 18, name: "Fries", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 245,
  },
  {
    id: 8,
    name: "Shawarma Chicken",
    category: "fast-food",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7FH8Xj3KgISbHQ7mVMKViQVWp27GcO.png",
    description: "Tasty chicken shawarma with fresh toppings",
    longDescription:
      "Grilled chicken wrapped in soft pita with crisp vegetables and our signature garlic sauce. A customer favorite!",
    addOns: [
      { id: 19, name: "Extra Chicken", price: 25 },
      { id: 20, name: "Extra Sauce", price: 5 },
      { id: 21, name: "Fries", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 278,
  },
  {
    id: 9,
    name: "Burger",
    category: "fast-food",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-gTzsAxe7oYy0c0lE2jmeeKimlOdLFR.png",
    description: "Classic beef burger with fresh toppings",
    longDescription:
      "Juicy beef patty with lettuce, tomato, onions, pickles, and our special burger sauce on a toasted bun.",
    addOns: [
      { id: 22, name: "Extra Patty", price: 30 },
      { id: 23, name: "Cheese", price: 10 },
      { id: 24, name: "Bacon", price: 15 },
    ],
    rating: 4.6,
    reviewCount: 201,
  },
  {
    id: 10,
    name: "Egg Burger",
    category: "fast-food",
    price: 120,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-r1S2SpmLukPNgqRehsvlF7HcQrTS3p.png",
    description: "Burger with fried egg and beef patty",
    longDescription:
      "Our classic burger topped with a perfectly fried egg. The combination of runny yolk and juicy beef is irresistible!",
    addOns: [
      { id: 25, name: "Extra Egg", price: 15 },
      { id: 26, name: "Cheese", price: 10 },
      { id: 27, name: "Fries", price: 20 },
    ],
    rating: 4.7,
    reviewCount: 192,
  },
  {
    id: 11,
    name: "Double Burger",
    category: "fast-food",
    price: 170,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-krCIXFMcSBukIZaTxODUPrSyPPAX9t.png",
    description: "Double beef patty burger for big appetites",
    longDescription:
      "Two juicy beef patties stacked high with cheese, lettuce, tomato, and our special sauce. For those with a hearty appetite!",
    addOns: [
      { id: 28, name: "Extra Patty", price: 40 },
      { id: 29, name: "Bacon", price: 15 },
      { id: 30, name: "Fries", price: 20 },
    ],
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 12,
    name: "Ice Cream Small",
    category: "drinks",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cream-LLQ3LSvijGkqTbPBJicnaMTQOfwUgs.jpg",
    description: "Small serving of creamy ice cream",
    longDescription: "Cool and creamy ice cream in various flavors. Perfect for a sweet treat!",
    addOns: [
      { id: 31, name: "Extra Scoop", price: 10 },
      { id: 32, name: "Toppings", price: 5 },
    ],
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: 13,
    name: "Ice Cream Large",
    category: "drinks",
    price: 50,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cream%201-KUmozZfzOikgIjvuN7kYWfQnJAwe2X.jpg",
    description: "Large serving of delicious ice cream",
    longDescription:
      "Generous portion of our creamy ice cream. Available in multiple flavors to satisfy your sweet tooth.",
    addOns: [
      { id: 33, name: "Extra Scoop", price: 15 },
      { id: 34, name: "Toppings", price: 8 },
    ],
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: 14,
    name: "Foofoo with Okra Soup",
    category: "african",
    price: 120,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Foofoo%20okara%20suap-UMxkpqwGcyF8Q9iT8MnWbotSFxipD6.jpg",
    description: "Traditional African foofoo with okra soup",
    longDescription:
      "Smooth and stretchy foofoo served with rich okra soup and tender meat. A traditional African staple that's both filling and delicious.",
    addOns: [
      { id: 35, name: "Extra Foofoo", price: 30 },
      { id: 36, name: "Extra Soup", price: 25 },
      { id: 37, name: "Fish", price: 30 },
    ],
    rating: 4.7,
    reviewCount: 145,
  },
  {
    id: 15,
    name: "Birthday Cake Small",
    category: "bakery",
    price: 350,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20cake%20350-M9U0vI1CYXs9XJxgZXxB7qCn89LYIl.jpg",
    description: "Small birthday cake for intimate celebrations",
    longDescription:
      "Beautiful birthday cake perfect for small gatherings. Available in various flavors and can be customized with a message. For customized designs message on WhatsApp +232 78 891638.",
    addOns: [
      { id: 38, name: "Custom Message", price: 10 },
      { id: 39, name: "Candles", price: 5 },
    ],
    featured: true,
  },
  {
    id: 16,
    name: "Birthday Cake Medium",
    category: "bakery",
    price: 550,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20Cake%20550-aDjYxWfat7XZ0J5d4puKB8EI4ydk1Y.jpg",
    description: "Medium birthday cake for family celebrations",
    longDescription:
      "Perfect sized cake for family birthday celebrations. Choose from chocolate, vanilla, or red velvet flavors. Can be customized with your child's favorite themes! For customized designs message on WhatsApp +232 78 891638.",
    addOns: [
      { id: 40, name: "Custom Message", price: 10 },
      { id: 41, name: "Candles", price: 5 },
    ],
  },
  {
    id: 17,
    name: "Customize Order",
    category: "bakery",
    price: 0,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20cake%202500-scV0HFXBrDDXf02a6v4vFb4SuVHEpM.jpg",
    description: "Custom birthday cake - message us for your design!",
    longDescription:
      "Large celebration cake perfect for parties. Beautifully decorated with intricate designs. Multiple flavor options available. For customized designs message on WhatsApp +232 78 891638.",
    addOns: [
      { id: 42, name: "Custom Message", price: 15 },
      { id: 43, name: "Candles", price: 8 },
    ],
  },
  {
    id: 18,
    name: "Customized Cake Design",
    category: "bakery",
    price: 0,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/customize%20Cake%203-5NN7FvpOc8MZ4Qsf9RBz7flNGiVJ02.jpg",
    images: [
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/customize%20Cake%203-5NN7FvpOc8MZ4Qsf9RBz7flNGiVJ02.jpg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/customize%20Cake-7nOzODXuuEbfptAD3KHT9pEl9RMGZf.jpg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/customize%20Cake%204-kAYaKaLtKy2Ilsl1AewccFaaiRfLo8.jpg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/customize%20Cake%202-ofFoVsnmQLAuxRUxPUC1Ogd1cXrKyi.jpg",
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Birthday%20cake%202500-scV0HFXBrDDXf02a6v4vFb4SuVHEpM.jpg",
    ],
    description: "Create your dream cake with personalized designs and themes",
    longDescription:
      "Bring your vision to life with our fully customized cake designs! From princess castles to superhero adventures, birthday milestones to wedding celebrations - we create stunning custom cakes tailored to your exact specifications. Every cake is a masterpiece crafted with love and attention to detail. Contact us on WhatsApp to discuss your design ideas, theme, size, flavors, and budget. Our talented bakers will work with you to create the perfect cake for your special occasion!",
    addOns: [],
    isCustomizable: true,
    featured: true,
  },
  {
    id: 19,
    name: "Rich Cake",
    category: "bakery",
    price: 50,
    image: "/rich-cake-trays.jpg",
    description: "Moist and rich cake slice",
    longDescription:
      "Dense, moist, and incredibly rich cake. Perfect with a cup of tea or coffee. A decadent treat for any time of day.",
    addOns: [
      { id: 46, name: "Extra Slice", price: 50 },
      { id: 47, name: "Ice Cream", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 20,
    name: "Banana Bread",
    category: "bakery",
    price: 65,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Banana%20bread-GQZfy18LuYq3tX05fv2wxGMBeIFoNZ.jpg",
    description: "Small loaf of homemade banana bread",
    longDescription:
      "Moist and flavorful banana bread made with ripe bananas. Perfect for breakfast or as a snack with tea.",
    addOns: [
      { id: 48, name: "Butter", price: 5 },
      { id: 49, name: "Extra Slice", price: 15 },
    ],
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 22,
    name: "Pizza",
    category: "fast-food",
    price: 250,
    image: "/pizza.jpg",
    description: "Delicious pepperoni pizza with melted cheese - Choose your size!",
    longDescription:
      "Hot and fresh pizza loaded with pepperoni, mozzarella cheese, and our signature tomato sauce. Perfectly baked with a crispy crust. Available in Small, Medium, and Large sizes!",
    variants: [
      {
        id: 1,
        name: "Small Pizza",
        price: 250,
        description: "Perfect for 1-2 people",
      },
      {
        id: 2,
        name: "Medium Pizza",
        price: 300,
        description: "Great for 2-3 people",
      },
      {
        id: 3,
        name: "Large Pizza",
        price: 350,
        description: "Feeds 3-4 people",
      },
    ],
    addOns: [
      { id: 52, name: "Extra Cheese", price: 20 },
      { id: 53, name: "Extra Pepperoni", price: 25 },
      { id: 54, name: "Mushrooms", price: 15 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: 23,
    name: "Sausage Roll",
    category: "bakery",
    price: 20,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202025-11-06%20at%2019.18.02_96d1adb7-LioEbKmoGPqnZE2OebJ34yfPrFookY.jpg",
    description: "Freshly baked sausage rolls",
    longDescription:
      "Golden brown sausage rolls made fresh daily. Flaky pastry wrapped around seasoned sausage meat. Perfect for a quick snack!",
    addOns: [
      { id: 55, name: "Extra Roll", price: 20 },
      { id: 56, name: "Ketchup", price: 5 },
    ],
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: 24,
    name: "Red Bull",
    category: "drinks",
    price: 60,
    image: "/redbull.jpeg",
    description: "Red Bull Energy Drink",
    longDescription: "Ice cold Red Bull energy drink to keep you energized throughout the day.",
    addOns: [],
    rating: 4.6,
    reviewCount: 78,
  },
  {
    id: 25,
    name: "Vimto",
    category: "drinks",
    price: 35,
    image: "/vimto-drink.jpg",
    description: "Vimto Sparkling Drink",
    longDescription: "Refreshing Vimto sparkling drink with mixed fruit flavors. A delicious and fizzy treat!",
    addOns: [],
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: 26,
    name: "Coca Cola",
    category: "drinks",
    price: 30,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cock-OKpuLbq3Smq9JWt4x6RgSVjxpF7N2A.jpeg",
    description: "Coca-Cola classic",
    longDescription: "Ice cold Coca-Cola. The classic refreshing cola!",
    addOns: [],
  },
  {
    id: 27,
    name: "Super Malt",
    category: "drinks",
    price: 65,
    image: "/super-malt.jpg",
    description: "Super Malt Original",
    longDescription:
      "Non-alcoholic malt beverage with B vitamins. Rich, smooth taste that's both nutritious and delicious.",
    addOns: [],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 28,
    name: "Fanta",
    category: "drinks",
    price: 30,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Ice%20cold%20fanta-qQNGGuht2bRfqVLzznJhdI4U1UuyqA.jpeg",
    description: "Fanta Orange",
    longDescription: "Refreshing Fanta Orange soda. Perfect for quenching your thirst on a hot day!",
    addOns: [],
  },
  {
    id: 29,
    name: "Kebba",
    category: "african",
    price: 25,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Kebba-wTBvhmk8yXmeOjmIfqX8qW9QHd2hTA.jpg",
    description: "Traditional African Kebba",
    longDescription:
      "Delicious traditional African kebba, crispy on the outside and flavorful on the inside. A beloved street food delicacy!",
    addOns: [
      { id: 57, name: "Extra Sauce", price: 5 },
      { id: 58, name: "Extra Pieces", price: 30 },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 234,
  },
  {
    id: 30,
    name: "Laffadie Special",
    category: "african",
    price: 150,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Laffadie%20150-g20b02jrCgZ6rwZHy1YCStGigAa16y.jpg",
    description: "Laffadie rice with sausages and fried items",
    longDescription:
      "A complete Laffadie meal featuring white rice, sausages, crispy fried items, and special spices. A hearty traditional favorite!",
    addOns: [
      { id: 59, name: "Extra Sausage", price: 20 },
      { id: 60, name: "Extra Rice", price: 15 },
    ],
    rating: 4.9,
    reviewCount: 187,
  },
  {
    id: 31,
    name: "Maltina",
    category: "drinks",
    price: 35,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Maltina-w1L5rUpnTXcQXagYGs4YutmG3FQMgp.jpeg",
    description: "Maltina Classic Malt Drink",
    longDescription: "Enriched non-alcoholic malt beverage with B vitamins. Smooth, refreshing, and nutritious!",
    addOns: [],
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: 32,
    name: "Lucozade Energy",
    category: "drinks",
    price: 35,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Lucozade%20Drink-FMcU3DK8mTtSzZPDnQa37vEbURrpsD.jpg",
    description: "Lucozade Energy Orange",
    longDescription:
      "Ice-cold Lucozade Energy drink with glucose to keep you powered throughout the day. Refreshing orange flavor!",
    addOns: [],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 33,
    name: "Krain Krain",
    category: "african",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/krain%20krain-6wBSS2WtipNx50vqemm8Zi3hrhP0JZ.jpg",
    description: "Traditional Krain Krain stew with meat",
    longDescription:
      "Rich, traditional Krain Krain stew cooked with tender meat, seafood, and special spices. A West African delicacy from Pee's Bakery!",
    addOns: [
      { id: 61, name: "Extra Meat", price: 40 },
      { id: 62, name: "Extra Seafood", price: 50 },
      { id: 63, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 143,
  },
  {
    id: 34,
    name: "Fish Balls",
    category: "african",
    price: 10,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Fish%20Ball-CmEMGPt5srcWX3yNh3w0BBxZ0J4Vga.jpg",
    description: "Crispy fried fish balls - 10 GMD for 1pc, 100 GMD for 12pcs with veg",
    longDescription:
      "Golden fried fish balls made with fresh fish and special seasonings. Crispy on the outside, tender on the inside. A popular snack! 10 GMD for 1 piece or 100 GMD for 12 pieces with vegetables.",
    addOns: [
      { id: 70, name: "Extra Sauce", price: 5 },
      { id: 71, name: "12 Pieces with Veg", price: 90 },
    ],
    rating: 4.6,
    reviewCount: 134,
  },
  {
    id: 35,
    name: "Chicken Balls",
    category: "fast-food",
    price: 80,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chinken%20ball-WvE4Dpis0CBmTAf5gFdFRsy4ADphap.jpg",
    description: "Pack of 12 crispy chicken balls with vegetables",
    longDescription:
      "Golden fried chicken balls made with tender chicken and special seasonings. Pack of 12 pieces served with fresh vegetables. Perfect for sharing!",
    addOns: [
      { id: 72, name: "Extra Sauce", price: 5 },
      { id: 73, name: "Extra Vegetables", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: 36,
    name: "Meat Pie",
    category: "bakery",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-t03EuVJC5nGswH4Ge3oFoeqOgpkXve.png",
    description: "Freshly baked meat pie",
    longDescription:
      "Flaky pastry filled with seasoned ground beef and vegetables. Baked fresh daily. Perfect for a quick snack or light meal!",
    addOns: [
      { id: 74, name: "Extra Pie", price: 20 },
      { id: 75, name: "Ketchup", price: 5 },
    ],
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: 37,
    name: "Gizzard on Stick",
    category: "african",
    price: 20,
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Gizzard%20on%20stick-UyeDFuvx2zlLX1Uuikuf1s6N5TyXZb.jpg",
    description: "Tender grilled gizzards on stick",
    longDescription:
      "Succulent grilled gizzards seasoned with African spices and grilled to perfection. A delicious street food favorite!",
    addOns: [
      { id: 76, name: "Extra Skewer", price: 20 },
      { id: 77, name: "Extra Sauce", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 178,
  },
  {
    id: 38,
    name: "Pork Stick",
    category: "african",
    price: 35,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-eUyuX1lq5xrLPr5Dcgh0RXAWKiSbnL.png",
    description: "Grilled pork on stick",
    longDescription:
      "Tender pork pieces marinated and grilled on skewers. Juicy, flavorful, and perfectly seasoned. A popular street food choice!",
    addOns: [
      { id: 78, name: "Extra Stick", price: 35 },
      { id: 79, name: "Extra Sauce", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 39,
    name: "Spring Roll",
    category: "fast-food",
    price: 10,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-xpdUD2p9dsLHOIEuACjAeNyRgxlAHe.png",
    description: "Crispy vegetable spring roll",
    longDescription:
      "Crispy fried spring rolls filled with mixed vegetables and special seasonings. Perfect as a snack or appetizer!",
    addOns: [
      { id: 80, name: "Extra Roll", price: 10 },
      { id: 81, name: "Sweet Chili Sauce", price: 5 },
    ],
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: 40,
    name: "Crispy Chicken",
    category: "african",
    price: 35,
    image: "/crispy-fried-chicken.png",
    description: "Crispy fried chicken pieces",
    longDescription:
      "Golden fried chicken with a crispy coating. Seasoned to perfection with our special blend of spices. Juicy and flavorful!",
    addOns: [
      { id: 82, name: "Extra Piece", price: 35 },
      { id: 83, name: "Fries", price: 20 },
      { id: 84, name: "Coleslaw", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 201,
  },
  {
    id: 41,
    name: "Bread",
    category: "bakery",
    price: 25,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bread-Nz38OenycM4E2YYmfg2gv5m0xWgW1D.jpg",
    description: "Fresh baked bread loaf",
    longDescription:
      "Soft and fresh white bread loaf baked daily. Perfect for sandwiches or toast. Made with quality ingredients!",
    addOns: [
      { id: 85, name: "Butter", price: 5 },
      { id: 86, name: "Jam", price: 8 },
    ],
    rating: 4.5,
    reviewCount: 123,
  },
  {
    id: 42,
    name: "Brown Bread",
    category: "bakery",
    price: 35,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Brown%20Bread-fPUByO1zeZwRvqkOXTo68ewmOmQB0c.jpg",
    description: "Healthy whole wheat brown bread",
    longDescription:
      "Nutritious brown bread made with whole wheat flour. Higher in fiber and perfect for a healthy diet. Freshly baked!",
    addOns: [
      { id: 87, name: "Butter", price: 5 },
      { id: 88, name: "Honey", price: 10 },
    ],
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: 43,
    name: "Grilled Fish Selection",
    category: "african",
    price: 350,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Grilled%20fish-K9r93nch5a9rNEF4aZRPWCBLljQmvX.jpg",
    description: "Choose from our selection of grilled fish options",
    longDescription:
      "Select your preferred grilled fish option from our menu. All options are grilled to perfection with our special blend of spices and served with delicious sides!",
    variants: [
      {
        id: 1,
        name: "Grilled Catfish with Fries",
        price: 350,
        description: "Whole grilled catfish with fries, plantain and coleslaw",
      },
      {
        id: 2,
        name: "Grilled Catfish with Fried Rice",
        price: 400,
        description: "Whole grilled catfish with fried rice, plantain and coleslaw",
      },
      {
        id: 3,
        name: "Grilled Fish (Regular)",
        price: 350,
        description: "Regular size whole grilled fish with sides",
      },
      {
        id: 4,
        name: "Grilled Fish (Large)",
        price: 550,
        description: "Large size whole grilled fish with sides",
      },
    ],
    addOns: [
      { id: 89, name: "Extra Plantain", price: 20 },
      { id: 90, name: "Extra Fries", price: 20 },
      { id: 91, name: "Extra Sauce", price: 10 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 44,
    name: "Chin Chin",
    category: "bakery",
    price: 20,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Chin%20chin-EymquYewookdYTUoBiO4nMHzpZphmU.jpg",
    description: "Crunchy West African chin chin",
    longDescription:
      "Traditional West African crunchy snack made with flour, sugar, and spices. Sweet, crispy, and perfect for munching anytime!",
    addOns: [{ id: 92, name: "Extra Portion", price: 20 }],
    rating: 4.7,
    reviewCount: 145,
  },
  {
    id: 45,
    name: "Potato Leaves Crain Crain",
    category: "african",
    price: 100,
    image: "/potato-leaves.jpg",
    description: "Traditional West African potato leaves stew",
    longDescription:
      "Rich and flavorful potato leaves cooked with meat, fish, and authentic African spices. A beloved traditional dish from Pee's Bakery!",
    addOns: [
      { id: 93, name: "Extra Meat", price: 40 },
      { id: 94, name: "Extra Fish", price: 40 },
      { id: 95, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 167,
  },
  {
    id: 46,
    name: "Okra",
    category: "african",
    price: 100,
    image: "/okra.jpg",
    description: "Traditional okra soup - Choose Foofoo or Rice!",
    longDescription:
      "Delicious okra soup prepared with meat, fish, and authentic African spices. Served with your choice of Foofoo or Rice. A traditional favorite!",
    variants: [
      {
        id: 1,
        name: "Okra with Foofoo",
        price: 120,
        description: "Okra soup served with smooth foofoo",
      },
      {
        id: 2,
        name: "Okra with Rice",
        price: 100,
        description: "Okra soup served with white rice",
      },
    ],
    addOns: [
      { id: 96, name: "Extra Meat", price: 40 },
      { id: 97, name: "Extra Fish", price: 40 },
      { id: 98, name: "Extra Soup", price: 25 },
    ],
    featured: true,
  },
  {
    id: 47,
    name: "Beans",
    category: "african",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Bean%27s-hyAASVJdcpCw97CJlPObKFtuFUcILs.jpg",
    description: "Rich and savory beans",
    longDescription:
      "Traditional beans cooked with meat and vegetables. Flavorful and satisfying. A West African classic!",
    addOns: [
      { id: 99, name: "Extra Meat", price: 40 },
      { id: 100, name: "Rice", price: 20 },
      { id: 101, name: "Foofoo", price: 30 },
    ],
  },
  {
    id: 48,
    name: "Stew",
    category: "african",
    price: 100,
    image: "/stew.png",
    description: "Traditional African stew with meat and rice",
    longDescription:
      "Rich and flavorful African stew cooked with meat, vegetables, and aromatic spices. Served with rice!",
    addOns: [
      { id: 102, name: "Extra Meat", price: 40 },
      { id: 103, name: "Extra Rice", price: 20 },
      { id: 104, name: "Bulgur", price: 20 },
    ],
  },
  {
    id: 49,
    name: "Rice or Bulgur",
    category: "african",
    price: 100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bulgur-51MinKIMuIfRwxBQGL3GKgxQyl9lm5.jpg",
    description: "White rice or bulgur wheat side dish",
    longDescription:
      "Choose between fluffy white rice or nutritious bulgur wheat. Perfect as a side or base for your favorite African stew!",
    addOns: [
      { id: 105, name: "Extra Portion", price: 20 },
      { id: 106, name: "Plantain", price: 15 },
    ],
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: 50,
    name: "Cassava Leaf",
    category: "african",
    price: 100,
    image: "/cassava-leaf.jpg",
    description: "Traditional cassava leaf stew",
    longDescription:
      "Authentic cassava leaf stew cooked with meat, fish, and traditional spices. A beloved West African delicacy from Pee's Bakery!",
    addOns: [
      { id: 107, name: "Extra Meat", price: 40 },
      { id: 108, name: "Extra Fish", price: 40 },
      { id: 109, name: "Rice", price: 20 },
      { id: 110, name: "Foofoo", price: 30 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 187,
  },
  {
    id: 51,
    name: "Savanna Cider",
    category: "drinks",
    price: 50,
    image: "/savanna-cider.jpg",
    description: "Savanna Premium Dry Cider",
    longDescription:
      "Refreshing Savanna Premium Dry Cider. Crisp, cold, and perfect for any occasion. Enjoy the taste of premium cider!",
    addOns: [],
  },
  {
    id: 52,
    name: "Sierra Box Juice",
    category: "drinks",
    price: 10,
    image: "/sierra-mango-juice.jpg",
    description: "Sierra Mango Nectar Box Juice",
    longDescription:
      "Delicious Sierra brand mango nectar juice enriched with Vitamin C. Sweet, refreshing, and perfect for any time of day!",
    variants: [
      {
        id: 1,
        name: "Sierra Mango",
        price: 10,
        description: "Mango nectar juice",
      },
      {
        id: 2,
        name: "Sierra Orange",
        price: 10,
        description: "Orange juice",
      },
      {
        id: 3,
        name: "Sierra Pineapple",
        price: 10,
        description: "Pineapple juice",
      },
    ],
    addOns: [],
  },
  {
    id: 62,
    name: "Sierra Juice",
    category: "drinks",
    price: 15,
    image: "/sierra-juice.jpg",
    description: "Sierra Premium Juice Bottle",
    longDescription:
      "Premium Sierra juice in convenient bottle. Refreshing and delicious!",
    addOns: [],
  },
  {
    id: 63,
    name: "Sierra Water",
    category: "drinks",
    price: 12,
    image: "/sierra-water-big.jpg",
    description: "Sierra Pure Mineral Water - Choose your size!",
    longDescription:
      "Pure and refreshing Sierra mineral water. Available in Small and Big bottle sizes. Stay hydrated!",
    variants: [
      {
        id: 1,
        name: "Small Bottle",
        price: 8,
        description: "500ml bottle",
      },
      {
        id: 2,
        name: "Big Bottle",
        price: 12,
        description: "1.5L bottle",
      },
    ],
    addOns: [],
  },
  {
    id: 53,
    name: "Schweppes",
    category: "drinks",
    price: 65,
    image: "/schweppes.jpg",
    description: "Schweppes Carbonated Drinks",
    longDescription:
      "Classic Schweppes carbonated drinks. Crisp, refreshing, and perfect for mixing or enjoying on its own!",
    variants: [
      {
        id: 1,
        name: "Schweppes Soda Water",
        price: 65,
        description: "Carbonated soda water",
      },
      {
        id: 2,
        name: "Schweppes Tonic Water",
        price: 65,
        description: "Carbonated tonic water",
      },
    ],
    addOns: [],
  },
  {
    id: 54,
    name: "X-tra Juice",
    category: "drinks",
    price: 35,
    image: "/xtra-juice.jpg",
    description: "X-tra Premium Bottled Juice - Multiple flavors",
    longDescription:
      "Premium X-tra brand bottled juice enriched with vitamins. Available in Pineapple, Exotic, and other delicious flavors!",
    variants: [
      {
        id: 1,
        name: "X-tra Pineapple",
        price: 35,
        description: "Pineapple juice",
      },
      {
        id: 2,
        name: "X-tra Exotic",
        price: 35,
        description: "Exotic fruit juice",
      },
      {
        id: 3,
        name: "X-tra Orange",
        price: 35,
        description: "Orange juice",
      },
    ],
    addOns: [],
  },
  {
    id: 55,
    name: "Vita Milk",
    category: "drinks",
    price: 35,
    image: "/vita-milk.jpg",
    description: "Vita Milk Soy Drinks - Multiple flavors",
    longDescription:
      "Delicious Vita Milk soy drinks. 25% protein, enriched with vitamins and calcium. Nutritious and tasty!",
    variants: [
      {
        id: 1,
        name: "Vita Milk Banana",
        price: 35,
        description: "Banana flavored soy drink",
      },
      {
        id: 2,
        name: "Vita Milk Double Choco",
        price: 35,
        description: "Double chocolate shake",
      },
    ],
    addOns: [],
  },
  {
    id: 56,
    name: "Fontana Juice",
    category: "drinks",
    price: 85,
    image: "/fontana-juice.jpg",
    description: "Fontana Refreshing Juice - Multiple flavors",
    longDescription: "Delicious Fontana juice in convenient cartons. Fresh, sweet, and refreshing tropical flavors!",
    variants: [
      {
        id: 1,
        name: "Fontana Pineapple Juice",
        price: 85,
        description: "Pineapple juice",
      },
      {
        id: 2,
        name: "Fontana Cranberry Juice",
        price: 85,
        description: "Cranberry juice",
      },
    ],
    addOns: [],
  },
  {
    id: 57,
    name: "Countre Milk",
    category: "drinks",
    price: 55,
    image: "/countre-milk.jpg",
    description: "Countre Dairy Milk - Multiple flavors",
    longDescription: "Delicious Countre milk products. Creamy, sweet, and packed with nutrients. Perfect for any time!",
    variants: [
      {
        id: 1,
        name: "Countre Banana Milk",
        price: 55,
        description: "Banana flavored whole milk",
      },
      {
        id: 2,
        name: "Countre Whole Milk",
        price: 55,
        description: "UHT whole milk",
      },
      {
        id: 3,
        name: "Countre Vanilla Milk",
        price: 55,
        description: "Vanilla full cream milk",
      },
    ],
    addOns: [],
  },
  {
    id: 58,
    name: "Aloe Vera Drink",
    category: "drinks",
    price: 45,
    image: "/aloe-vera-drink.jpg",
    description: "Vinut Aloe Vera Original Drink",
    longDescription: "Refreshing Vinut aloe vera drink with real aloe vera pieces. Healthy, hydrating, and delicious!",
    addOns: [],
  },
  {
    id: 59,
    name: "Don Simon Juice",
    category: "drinks",
    price: 85,
    image: "/don-simon-juice.jpg",
    description: "Don Simon Premium Juice 1L - Multiple flavors",
    longDescription: "Premium Don Simon juice in large 1L cartons. Bursting with fruit flavors!",
    variants: [
      {
        id: 1,
        name: "Don Simon Tropical",
        price: 85,
        description: "Tropical fruit juice",
      },
      {
        id: 2,
        name: "Don Simon Orange",
        price: 85,
        description: "Orange juice",
      },
      {
        id: 3,
        name: "Don Simon Pineapple",
        price: 85,
        description: "Pineapple juice",
      },
    ],
    addOns: [],
  },
  {
    id: 60,
    name: "Ceres Juice",
    category: "drinks",
    price: 100,
    image: "/ceres-juice.jpg",
    description: "Ceres 100% Fruit Juice - Multiple flavors",
    longDescription:
      "Premium Ceres 100% fruit juice in 1L boxes. Available in Mango, Apple, Pineapple, and more delicious flavors!",
    variants: [
      {
        id: 1,
        name: "Ceres Mango",
        price: 100,
        description: "100% mango juice",
      },
      {
        id: 2,
        name: "Ceres Apple",
        price: 100,
        description: "100% apple juice",
      },
      {
        id: 3,
        name: "Ceres Pineapple",
        price: 100,
        description: "100% pineapple juice",
      },
    ],
    addOns: [],
  },
  {
    id: 61,
    name: "Small Robber Drink",
    category: "drinks",
    price: 10,
    image: "/small-robber-drink.jpg",
    description: "Small plastic bottle soft drinks",
    longDescription: "Small plastic bottle soft drinks. Perfect size for a quick refreshment!",
    variants: [
      {
        id: 1,
        name: "Sprite",
        price: 10,
        description: "Lemon-lime soda",
      },
      {
        id: 2,
        name: "Coca-Cola",
        price: 10,
        description: "Classic cola",
      },
      {
        id: 3,
        name: "Fanta",
        price: 10,
        description: "Orange soda",
      },
    ],
    addOns: [],
  },
]

export const categories = [
  { id: "all", name: "All Items" },
  { id: "african", name: "African Dishes" },
  { id: "bakery", name: "Bakery & Cakes" },
  { id: "fast-food", name: "Burgers & Shawarma" },
  { id: "drinks", name: "Drinks & Desserts" },
]
