import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Spaghetti",
    category: "african",
    price: 180,
    image: "/delicious-spaghetti-pasta-with-tomato-sauce.jpg",
    description: "Delicious spaghetti with rich tomato sauce and herbs",
    longDescription:
      "Our signature spaghetti is cooked to perfection with a rich tomato sauce, fresh herbs, and your choice of protein. A classic favorite that never disappoints.",
    addOns: [
      { id: 1, name: "Extra Meat", price: 30 },
      { id: 2, name: "Extra Cheese", price: 15 },
      { id: 3, name: "Garlic Bread", price: 20 },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 2,
    name: "Whole Chicken",
    category: "african",
    price: 250,
    image: "/roasted-whole-chicken-golden-brown.jpg",
    description: "Perfectly roasted whole chicken with seasoning",
    longDescription:
      "A full roasted chicken seasoned with our special blend of spices. Perfect for sharing with family and friends.",
    addOns: [
      { id: 4, name: "Extra Sauce", price: 10 },
      { id: 5, name: "Fried Plantain", price: 15 },
      { id: 6, name: "Coleslaw", price: 10 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 198,
  },
  {
    id: 3,
    name: "Half Chicken",
    category: "african",
    price: 150,
    image: "/half-roasted-chicken-with-herbs.jpg",
    description: "Half roasted chicken with special seasoning",
    longDescription:
      "Half of our perfectly roasted chicken, ideal for a single serving or smaller appetite. Seasoned to perfection.",
    addOns: [
      { id: 7, name: "Extra Sauce", price: 10 },
      { id: 8, name: "Fried Plantain", price: 15 },
      { id: 9, name: "Rice", price: 20 },
    ],
    featured: true,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: 4,
    name: "Bulgur with Fish",
    category: "african",
    price: 250,
    image: "/bulgur-fish.jpg",
    description: "Nutritious bulgur wheat served with fresh fish",
    longDescription:
      "Healthy bulgur wheat cooked with vegetables and served with perfectly seasoned fish. A nutritious and delicious meal.",
    addOns: [
      { id: 10, name: "Extra Fish", price: 40 },
      { id: 11, name: "Extra Vegetables", price: 15 },
    ],
    featured: true,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 5,
    name: "Fried Rice and Fish",
    category: "african",
    price: 250,
    image: "/fried-rice-with-fish-vegetables.jpg",
    description: "Flavorful fried rice with seasoned fish",
    longDescription:
      "Our special fried rice loaded with vegetables and served with perfectly fried fish. A complete and satisfying meal.",
    addOns: [
      { id: 12, name: "Extra Fish", price: 40 },
      { id: 13, name: "Plantain", price: 15 },
    ],
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: 6,
    name: "Fried Rice and Chicken",
    category: "african",
    price: 180,
    image: "/fried-rice-chicken.jpg",
    description: "Tasty fried rice with tender chicken",
    longDescription:
      "Delicious fried rice with mixed vegetables and tender chicken pieces. A popular choice for lunch or dinner.",
    addOns: [
      { id: 14, name: "Extra Chicken", price: 30 },
      { id: 15, name: "Coleslaw", price: 10 },
    ],
    rating: 4.7,
    reviewCount: 212,
  },
  {
    id: 7,
    name: "Shawarma Meat",
    category: "fast-food",
    price: 120,
    image: "/meat-shawarma-wrap-fresh-vegetables.jpg",
    description: "Delicious meat shawarma wrap with fresh vegetables",
    longDescription:
      "Tender marinated meat wrapped in fresh pita bread with lettuce, tomatoes, onions, and our special sauce.",
    addOns: [
      { id: 16, name: "Extra Meat", price: 30 },
      { id: 17, name: "Extra Sauce", price: 5 },
      { id: 18, name: "Fries", price: 20 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 245,
  },
  {
    id: 8,
    name: "Shawarma Chicken",
    category: "fast-food",
    price: 100,
    image: "/chicken-shawarma-wrap-garlic-sauce.jpg",
    description: "Tasty chicken shawarma with fresh toppings",
    longDescription:
      "Grilled chicken wrapped in soft pita with crisp vegetables and our signature garlic sauce. A customer favorite!",
    addOns: [
      { id: 19, name: "Extra Chicken", price: 25 },
      { id: 20, name: "Extra Sauce", price: 5 },
      { id: 21, name: "Fries", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 278,
  },
  {
    id: 9,
    name: "Burger",
    category: "fast-food",
    price: 100,
    image: "/classic-beef-burger-lettuce-tomato.jpg",
    description: "Classic beef burger with fresh toppings",
    longDescription:
      "Juicy beef patty with lettuce, tomato, onions, pickles, and our special burger sauce on a toasted bun.",
    addOns: [
      { id: 22, name: "Extra Patty", price: 30 },
      { id: 23, name: "Cheese", price: 10 },
      { id: 24, name: "Bacon", price: 15 },
    ],
    rating: 4.6,
    reviewCount: 201,
  },
  {
    id: 10,
    name: "Egg Burger",
    category: "fast-food",
    price: 120,
    image: "/burger-with-fried-egg-beef-patty.jpg",
    description: "Burger with fried egg and beef patty",
    longDescription:
      "Our classic burger topped with a perfectly fried egg. The combination of runny yolk and juicy beef is irresistible!",
    addOns: [
      { id: 25, name: "Extra Egg", price: 15 },
      { id: 26, name: "Cheese", price: 10 },
      { id: 27, name: "Fries", price: 20 },
    ],
    rating: 4.7,
    reviewCount: 192,
  },
  {
    id: 11,
    name: "Double Burger",
    category: "fast-food",
    price: 170,
    image: "/double-beef-burger-cheese-stacked.jpg",
    description: "Double beef patty burger for big appetites",
    longDescription:
      "Two juicy beef patties stacked high with cheese, lettuce, tomato, and our special sauce. For those with a hearty appetite!",
    addOns: [
      { id: 28, name: "Extra Patty", price: 40 },
      { id: 29, name: "Bacon", price: 15 },
      { id: 30, name: "Fries", price: 20 },
    ],
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: 12,
    name: "Ice Cream Small",
    category: "drinks",
    price: 20,
    image: "/ice-cream-cone-vanilla-chocolate.jpg",
    description: "Small serving of creamy ice cream",
    longDescription: "Cool and creamy ice cream in various flavors. Perfect for a sweet treat!",
    addOns: [
      { id: 31, name: "Extra Scoop", price: 10 },
      { id: 32, name: "Toppings", price: 5 },
    ],
    rating: 4.5,
    reviewCount: 167,
  },
  {
    id: 13,
    name: "Ice Cream Large",
    category: "drinks",
    price: 50,
    image: "/large-ice-cream-sundae-toppings.jpg",
    description: "Large serving of delicious ice cream",
    longDescription:
      "Generous portion of our creamy ice cream. Available in multiple flavors to satisfy your sweet tooth.",
    addOns: [
      { id: 33, name: "Extra Scoop", price: 15 },
      { id: 34, name: "Toppings", price: 8 },
    ],
    rating: 4.6,
    reviewCount: 189,
  },
  {
    id: 14,
    name: "Foofoo",
    category: "african",
    price: 120,
    image: "/african-foofoo-with-soup.jpg",
    description: "Traditional African foofoo with soup",
    longDescription:
      "Smooth and stretchy foofoo served with your choice of soup. A traditional African staple that's both filling and delicious.",
    addOns: [
      { id: 35, name: "Extra Foofoo", price: 30 },
      { id: 36, name: "Extra Soup", price: 25 },
      { id: 37, name: "Fish", price: 30 },
    ],
    rating: 4.7,
    reviewCount: 145,
  },
  {
    id: 15,
    name: "Birthday Cake Small",
    category: "bakery",
    price: 350,
    image: "/small-birthday-cake-decorated.jpg",
    description: "Small birthday cake for intimate celebrations",
    longDescription:
      "Beautiful birthday cake perfect for small gatherings. Available in various flavors and can be customized with a message.",
    addOns: [
      { id: 38, name: "Custom Message", price: 10 },
      { id: 39, name: "Candles", price: 5 },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: 16,
    name: "Birthday Cake Medium",
    category: "bakery",
    price: 550,
    image: "/medium-birthday-cake-colorful.jpg",
    description: "Medium birthday cake for family celebrations",
    longDescription:
      "Perfect sized cake for family birthday celebrations. Choose from chocolate, vanilla, or red velvet flavors.",
    addOns: [
      { id: 40, name: "Custom Message", price: 10 },
      { id: 41, name: "Candles", price: 5 },
    ],
    rating: 4.9,
    reviewCount: 112,
  },
  {
    id: 17,
    name: "Birthday Cake Large",
    category: "bakery",
    price: 750,
    image: "/large-birthday-cake-elegant.jpg",
    description: "Large birthday cake for big celebrations",
    longDescription:
      "Large celebration cake perfect for parties. Beautifully decorated and delicious. Multiple flavor options available.",
    addOns: [
      { id: 42, name: "Custom Message", price: 15 },
      { id: 43, name: "Candles", price: 8 },
    ],
    rating: 5.0,
    reviewCount: 87,
  },
  {
    id: 18,
    name: "Birthday Cake Extra Large",
    category: "bakery",
    price: 1000,
    image: "/placeholder.svg?height=400&width=400",
    description: "Extra large cake for grand celebrations",
    longDescription:
      "Our grandest birthday cake for large celebrations. Stunning design and exceptional taste. Perfect for milestone birthdays!",
    addOns: [
      { id: 44, name: "Custom Message", price: 20 },
      { id: 45, name: "Candles", price: 10 },
    ],
    rating: 5.0,
    reviewCount: 65,
  },
  {
    id: 19,
    name: "Rich Cake",
    category: "bakery",
    price: 50,
    image: "/placeholder.svg?height=400&width=400",
    description: "Moist and rich cake slice",
    longDescription:
      "Dense, moist, and incredibly rich cake. Perfect with a cup of tea or coffee. A decadent treat for any time of day.",
    addOns: [
      { id: 46, name: "Extra Slice", price: 50 },
      { id: 47, name: "Ice Cream", price: 20 },
    ],
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: 20,
    name: "Banana Bread Small",
    category: "bakery",
    price: 50,
    image: "/placeholder.svg?height=400&width=400",
    description: "Small loaf of homemade banana bread",
    longDescription:
      "Moist and flavorful banana bread made with ripe bananas. Perfect for breakfast or as a snack with tea.",
    addOns: [
      { id: 48, name: "Butter", price: 5 },
      { id: 49, name: "Extra Slice", price: 15 },
    ],
    rating: 4.7,
    reviewCount: 134,
  },
  {
    id: 21,
    name: "Banana Bread Large",
    category: "bakery",
    price: 100,
    image: "/placeholder.svg?height=400&width=400",
    description: "Large loaf of homemade banana bread",
    longDescription:
      "Full-sized loaf of our delicious banana bread. Great for sharing or enjoying throughout the week.",
    addOns: [
      { id: 50, name: "Butter", price: 8 },
      { id: 51, name: "Jam", price: 10 },
    ],
    rating: 4.8,
    reviewCount: 145,
  },
]

export const categories = [
  { id: "all", name: "All Items" },
  { id: "african", name: "African Dishes" },
  { id: "bakery", name: "Bakery & Cakes" },
  { id: "fast-food", name: "Burgers & Shawarma" },
  { id: "drinks", name: "Drinks & Desserts" },
]
